version: 2
updates:

  # Maintain dependencies for gomod
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix-development: "chore(deps)"
